pitonisa:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 0.0.0.0
      user: postgres
      password: postgres
      port: 5432
      dbname: dwh_crc
      schema: dwh
      threads: 3
      keepalives_idle: 0